/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iphone_penny.glb -t -r public/models 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    screen: THREE.Mesh
    camera_bump: THREE.Mesh
    ring_telephoto: THREE.Mesh
    lens_telephoto: THREE.Mesh
    ring_wide: THREE.Mesh
    lens_wide: THREE.Mesh
    ring_ultrawide: THREE.Mesh
    lens_ultrawide: THREE.Mesh
    lens_flash: THREE.Mesh
    lens_lidar: THREE.Mesh
    action: THREE.Mesh
    volume_up: THREE.Mesh
    volume_down: THREE.Mesh
    power: THREE.Mesh
  }
  materials: {
    titanium_frame: THREE.MeshStandardMaterial
    back_glass: THREE.MeshStandardMaterial
    screen_display: THREE.MeshStandardMaterial
    lens_rings: THREE.MeshStandardMaterial
    lens_glass: THREE.MeshPhysicalMaterial
    buttons: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/iphone_penny.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.screen.geometry} material={materials.screen_display} />
      <mesh geometry={nodes.camera_bump.geometry} material={materials.back_glass} />
      <mesh geometry={nodes.ring_telephoto.geometry} material={materials.lens_rings} />
      <mesh geometry={nodes.lens_telephoto.geometry} material={materials.lens_glass} />
      <mesh geometry={nodes.ring_wide.geometry} material={materials.lens_rings} />
      <mesh geometry={nodes.lens_wide.geometry} material={materials.lens_glass} />
      <mesh geometry={nodes.ring_ultrawide.geometry} material={materials.lens_rings} />
      <mesh geometry={nodes.lens_ultrawide.geometry} material={materials.lens_glass} />
      <mesh geometry={nodes.lens_flash.geometry} material={materials.lens_glass} />
      <mesh geometry={nodes.lens_lidar.geometry} material={materials.lens_glass} />
      <mesh geometry={nodes.action.geometry} material={materials.buttons} />
      <mesh geometry={nodes.volume_up.geometry} material={materials.buttons} />
      <mesh geometry={nodes.volume_down.geometry} material={materials.buttons} />
      <mesh geometry={nodes.power.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Plane.geometry} material={materials.titanium_frame} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.back_glass} />
    </group>
  )
}

useGLTF.preload('/models/iphone_penny.glb')
